#!/bin/bash
### BEGIN INIT INFO
# Provides:          airplayer
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

NAME=airplayer

PIDFILE="/var/run/$NAME/$NAME.pid"
LOGFILE="/var/log/$NAME/$NAME.log"

PYTHON="/usr/bin/python"
DAEMON="path/to/airplayer"
DAEMON_OPTS="-d --pidfile $PIDFILE --logfile $LOGFILE"

COMMAND="$PYTHON $DAEMON"

USER=xbmc
GROUP=xbmc

mkdir -p /var/run/$NAME > /dev/null 2> /dev/null
chown $USER:$GROUP /var/run/$NAME

mkdir -p /var/log/$NAME > /dev/null 2> /dev/null
chown $USER:$GROUP /var/log/$NAME
 
case "$1" in
    start)
        echo -n "Starting $NAME: "
        start-stop-daemon --start -c $USER:$GROUP\
                --exec $COMMAND -- $DAEMON_OPTS
        echo $NAME
  ;;
    stop)
        if [ -e $PIDFILE ]
        then
                echo -n "Stopping $NAME: "
                start-stop-daemon --stop --pidfile $PIDFILE
                echo "$NAME"
        else
                echo "$NAME is not running, pidfile $PIDFILE not found."
        fi
  ;;
    restart)
        $0 stop
        $0 start
  ;;
    *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
  ;;
esac
exit $RETVAL